### ISSUE TITLE
EGI Secret Store: Create folder for a VO group

### ISSUE THREAD

**Issue by sebastian-luna-valero** [fedcloud-eu/vault-doc#2]
Hello,

In the `vo.pangeo.eu` VO we have created a group called `pangeo.admin`.

There is already a VO-wide space in:
```
https://secrets.egi.eu/ui/vault/secrets/secrets/list/vos/vo.pangeo.eu/
```
I assume this is mapped with:
```
urn:mace:egi.eu:group:vo.pangeo.eu:role=member#aai.egi.eu
```
Would it be possible to have a folder like
```
https://secrets.egi.eu/ui/vault/secrets/secrets/list/vos/vo.pangeo.eu/pangeo.admin
```
Only accessible by people with this entitlement:
```
urn:mace:egi.eu:group:vo.pangeo.eu:admins:role=member#aai.egi.eu
```
Best regards,
Sebastian

PS: Sorry for cross-posting: https://ggus.eu/?mode=ticket_info&ticket_id=167448 and not being directly related an issue with the documentation of the service but with the service itself.

**Comment by tdviet** [comment]
To be discussed via the GGUS ticket. Add to the ticket more subgroups if needed (cloud.egi.eu/admin?) to be solve at once

**Comment by sebastian-luna-valero** [comment]
Sure, many thanks!
